/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#F7F5F2',
        surface: '#fcf8ff',
        'surface-dim': '#dad7f3',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#efecff',
        'surface-container-high': '#e8e5ff',
        'surface-container-highest': '#e2e0fc',
        primary: '#002452',
        'primary-container': '#1b3a6b',
        'on-primary': '#ffffff',
        'on-primary-container': '#89a5dd',
        secondary: '#98471f',
        'secondary-container': '#fd9668',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#752d06',
        tertiary: '#002c16',
        'tertiary-container': '#004425',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#68b484',
        'on-surface': '#1a1a2e',
        'on-surface-variant': '#44474f',
        'outline-variant': '#c4c6d0',
        outline: '#747780',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        success: '#4CAF50',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['"Source Serif 4"', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        gutter: '24px',
        lg: '32px',
        xl: '48px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      boxShadow: {
        card: '0 4px 4px 0 rgba(0,0,0,0.05)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
